---
name: Automation Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    name: CD Build
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Testing Requirements
        run: sudo pip install -r requirements-test.txt

      - name: Lint
        run: openwisp-qa-check --skip-checkmigrations

      - name: Setup
        run: |
          echo "127.0.0.1 dashboard.openwisp.org api.openwisp.org" | sudo tee -a /etc/hosts

      - name: Login to Gitlab Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITLAB_DOCKER_REGISTRY_TOKEN }}

      # Skip image builds and tests since they were done when
      # publishing to Docker Hub
      - name: Build & Publish to GitLab Container Registry
        run: |
          make publish TAG=edge SKIP_BUILD=true SKIP_TESTS=true
